-- MySQL Script generated by MySQL Workbench
-- Wed May 31 21:45:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema quanlycongviec
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quanlycongviec
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quanlycongviec` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `quanlycongviec` ;

-- -----------------------------------------------------
-- Table `quanlycongviec`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlycongviec`.`role` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quanlycongviec`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlycongviec`.`project` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Ten` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `StartDate` DATE NULL DEFAULT NULL,
  `EndDate` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quanlycongviec`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlycongviec`.`user` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(255) NULL DEFAULT NULL,
  `Pass` VARCHAR(255) NULL DEFAULT NULL,
  `Ten` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `Tuoi` DATE NULL DEFAULT NULL,
  `Role` VARCHAR(255) NULL DEFAULT NULL,
  `IsActive` BIT(1) NULL DEFAULT NULL,
  `ID_Role` INT NULL DEFAULT NULL,
  `ID_Project` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ID_Role` (`ID_Role` ASC) VISIBLE,
  INDEX `ID_Project` (`ID_Project` ASC) VISIBLE,
  CONSTRAINT `user_ibfk_1`
    FOREIGN KEY (`ID_Role`)
    REFERENCES `quanlycongviec`.`role` (`ID`),
  CONSTRAINT `user_ibfk_2`
    FOREIGN KEY (`ID_Project`)
    REFERENCES `quanlycongviec`.`project` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quanlycongviec`.`contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlycongviec`.`contract` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `ID_Mem` INT NULL DEFAULT NULL,
  `ID_CEO` INT NULL DEFAULT NULL,
  `ThoiHan` INT NULL DEFAULT NULL,
  `NgayKy` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ID_Mem` (`ID_Mem` ASC) VISIBLE,
  INDEX `ID_CEO` (`ID_CEO` ASC) VISIBLE,
  CONSTRAINT `contract_ibfk_1`
    FOREIGN KEY (`ID_Mem`)
    REFERENCES `quanlycongviec`.`user` (`ID`),
  CONSTRAINT `contract_ibfk_2`
    FOREIGN KEY (`ID_CEO`)
    REFERENCES `quanlycongviec`.`user` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quanlycongviec`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlycongviec`.`task` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  `Status` INT NULL DEFAULT NULL,
  `ID_Project` INT NULL DEFAULT NULL,
  `ID_User` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `ID_User` (`ID_User` ASC) VISIBLE,
  INDEX `ID_Project` (`ID_Project` ASC) VISIBLE,
  CONSTRAINT `task_ibfk_1`
    FOREIGN KEY (`ID_User`)
    REFERENCES `quanlycongviec`.`user` (`ID`),
  CONSTRAINT `task_ibfk_2`
    FOREIGN KEY (`ID_Project`)
    REFERENCES `quanlycongviec`.`project` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
